name: XCOM2 Launcher MSBuild

on:
  push:
    branches: [ "actions-test" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    env:
        Solution_Name: /xcom2-launcher/xcom2-launcher.sln
        Output_Dir: AML-Complete
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Build application
      run: |
        msbuild $env:Solution_Name /t:Build /p:Configuration=Release /p:OutputPath=bin\Release /p:SkipGitVersion=true

    - name: Copy necessary files to output directory
      run: |
        New-Item -ItemType Directory -Path "$env:Output_Dir" | Out-Null

        Copy-Item -Path "bin\Release\*.exe" -Destination "$env:Output_Dir" -Force
        Copy-Item -Path "bin\Release\*.dll" -Destination "$env:Output_Dir" -Force
        Copy-Item -Path "bin\Release\*.config" -Destination "$env:Output_Dir" -Force
        Copy-Item -Path "bin\Release\*.pdb" -Destination "$env:Output_Dir" -Force

    - name: Create distribution package
      run: |
        Compress-Archive -Path "$env:Output_Dir\*" -DestinationPath "XCOM2_AlternativeModLauncher.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: xcom2-launcher-clean
        path: XCOM2_AlternativeModLauncher.zip